apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-scheduler
spec:
  template:
    spec:
      containers:
      - image: olorin/cloud-scheduler:latest
        env:
        - name: MODE
          value: "reinforcement"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
