apiVersion: apps/v1
kind: Deployment
metadata:
  name: regional-filter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regional-filter
  template:
    metadata:
      labels:
        app: regional-filter
    spec:
      containers:
      - name: regional-filter
        image: olorin/regional-filter:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: minio-storage
          mountPath: /data
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc
